### ISSUE TITLE
missing requirements

### ISSUE THREAD

**Issue by Eremiel** [aquasecurity/kube-hunter#151]
On ubuntu 18.04 with python Python 2.7.15+

```
root@DeepRed:~/kube-hunter/kube-hunter# pip install -r requirements.txt
Requirement already satisfied: enum34 in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 1))
Requirement already satisfied: netaddr in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 2))
Requirement already satisfied: netifaces in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 3))
Requirement already satisfied: scapy==2.4.3rc1 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 4))
Requirement already satisfied: requests in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 5))
Requirement already satisfied: PrettyTable in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 6))
Requirement already satisfied: urllib3<1.25,>=1.24.2 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 7))
Requirement already satisfied: ruamel.yaml in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 8))
Requirement already satisfied: requests_mock in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 9))
Requirement already satisfied: future in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 10))
Requirement already satisfied: ruamel.ordereddict; platform_python_implementation == "CPython" and python_version <= "2.7" in /usr/local/lib/python2.7/dist-packages (from ruamel.yaml->-r requirements.txt (line 8))
Requirement already satisfied: six in /usr/lib/python2.7/dist-packages (from requests_mock->-r requirements.txt (line 9))
```

I am getting this:
```
/usr/lib/python2.7/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.24.3) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Traceback (most recent call last):
  File "kube-hunter.py", line 37, in <module>
    from src.modules.report.plain import PlainReporter
  File "/root/kube-hunter/kube-hunter/src/__init__.py", line 1, in <module>
    from . import core
  File "/root/kube-hunter/kube-hunter/src/core/__init__.py", line 1, in <module>
    from . import types
  File "/root/kube-hunter/kube-hunter/src/core/types.py", line 81, in <module>
    from .events import handler # import is in the bottom to break import loops
  File "/root/kube-hunter/kube-hunter/src/core/events/__init__.py", line 1, in <module>
    from .handler import *
  File "/root/kube-hunter/kube-hunter/src/core/events/handler.py", line 12, in <module>
    from ...core.events.types import HuntFinished, Vulnerability, EventFilterBase
  File "/root/kube-hunter/kube-hunter/src/core/events/types/__init__.py", line 4, in <module>
    from .common import *
  File "/root/kube-hunter/kube-hunter/src/core/events/types/common.py", line 2, in <module>
    import requests
  File "/usr/lib/python2.7/dist-packages/requests/__init__.py", line 97, in <module>
    from . import utils
  File "/usr/lib/python2.7/dist-packages/requests/utils.py", line 26, in <module>
    from ._internal_utils import to_native_string
  File "/usr/lib/python2.7/dist-packages/requests/_internal_utils.py", line 11, in <module>
    from .compat import is_py2, builtin_str, str
  File "/usr/lib/python2.7/dist-packages/requests/compat.py", line 47, in <module>
    from urllib3.packages.ordered_dict import OrderedDict
ImportError: No module named ordered_dict
```

**Comment by Eremiel** [comment]
Solved by installing 
urllib3==1.22

**Comment by danielsagi** [comment]
Hi @Eremiel , we are stopping support for Python 2, you should consider switching to Python 3.
related #153
