### ISSUE TITLE
python2 is used instead of python3

### ISSUE THREAD

**Issue by lbudai74** [aquasecurity/kube-hunter#246]
### What happened

When trying to run the kube-hunter.py it throws the following error:
 $> ./kube-hunter.py 
Traceback (most recent call last):
  File "./kube-hunter.py", line 33, in <module>
    from src.modules.report.plain import PlainReporter
  File "/root/kube-hunter/src/__init__.py", line 1, in <module>
    from . import core
  File "/root/kube-hunter/src/core/__init__.py", line 1, in <module>
    from . import types
  File "/root/kube-hunter/src/core/types.py", line 81, in <module>
    from .events import handler # import is in the bottom to break import loops
  File "/root/kube-hunter/src/core/events/__init__.py", line 1, in <module>
    from .handler import *
  File "/root/kube-hunter/src/core/events/handler.py", line 5, in <module>
    from queue import Queue
ImportError: No module named queue

### Expected behavior
to work properly.

### Comment
On a centos 7.7 machine I have the afore mentioned issue. The problem is that the script starts by this line:
`#!/usr/bin/env python`
 which will start python2 instead of python3. If I'm modifying the first line to be python3 then it's OK.
Shouldn't there be python3 in the first line?

Kind regards,
Laszlo

**Comment by lbudai74** [comment]
Thanks for the quick fix.
