### ISSUE TITLE
Running kube-hunter.py is receiving an IndexError

### ISSUE THREAD

**Issue by yusufscott** [aquasecurity/kube-hunter#262]
### What happened

I received the following error when running `./kube-hunter.py`:

>Traceback (most recent call last):
  File "kube-hunter.py", line 33, in <module>
    from src.modules.report.plain import PlainReporter
  File "/Users/i25814/testspace/kube/kube-hunter/src/__init__.py", line 2, in <module>
    from . import modules
  File "/Users/i25814/testspace/kube/kube-hunter/src/modules/__init__.py", line 3, in <module>
    from . import hunting
  File "/Users/i25814/testspace/kube/kube-hunter/src/modules/hunting/__init__.py", line 3, in <module>
    from .dns import *
  File "/Users/i25814/testspace/kube/kube-hunter/src/modules/hunting/dns.py", line 8, in <module>
    from .arp import PossibleArpSpoofing
  File "/Users/i25814/testspace/kube/kube-hunter/src/modules/hunting/arp.py", line 9, in <module>
    from scapy.all import ARP, IP, ICMP, Ether, sr1, srp
  File "/Users/i25814/testspace/kube/kube-hunter/venv/lib/python3.7/site-packages/scapy/all.py", line 27, in <module>
    from scapy.route import *
  File "/Users/i25814/testspace/kube/kube-hunter/venv/lib/python3.7/site-packages/scapy/route.py", line 194, in <module>
    conf.route = Route()
  File "/Users/i25814/testspace/kube/kube-hunter/venv/lib/python3.7/site-packages/scapy/route.py", line 27, in __init__
    self.resync()
  File "/Users/i25814/testspace/kube/kube-hunter/venv/lib/python3.7/site-packages/scapy/route.py", line 35, in resync
    self.routes = read_routes()
  File "/Users/i25814/testspace/kube/kube-hunter/venv/lib/python3.7/site-packages/scapy/arch/unix.py", line 82, in read_routes
    netif = rt[4 + mtu_present + prio_present + refs_present + locked]
IndexError: list index out of range

`pip freeze` provides the following:

>certifi==2019.9.11
chardet==3.0.4
future==0.18.1
idna==2.8
netaddr==0.7.19
netifaces==0.10.9
packaging==19.2
prettytable==0.7.2
pyparsing==2.4.2
requests==2.22.0
requests-mock==1.7.0
ruamel.yaml==0.16.5
ruamel.yaml.clib==0.2.0
scapy==2.4.3rc1
six==1.12.0
urllib3==1.24.3

I am using python 3.7.4 in a virtualenv on MacOS 10.15

**Comment by adyrcz** [comment]
I received the same indexerror
```
Traceback (most recent call last):
  File "kube-hunter.py", line 33, in <module>
    from src.modules.report.plain import PlainReporter
  File "/Users/adyrcz/Linkfire/Security/kube-hunter/src/__init__.py", line 2, in <module>
    from . import modules
  File "/Users/adyrcz/Linkfire/Security/kube-hunter/src/modules/__init__.py", line 3, in <module>
    from . import hunting
  File "/Users/adyrcz/Linkfire/Security/kube-hunter/src/modules/hunting/__init__.py", line 7, in <module>
    exec('from .{} import *'.format(module_name))
  File "<string>", line 1, in <module>
  File "/Users/adyrcz/Linkfire/Security/kube-hunter/src/modules/hunting/dns.py", line 8, in <module>
    from .arp import PossibleArpSpoofing
  File "/Users/adyrcz/Linkfire/Security/kube-hunter/src/modules/hunting/arp.py", line 9, in <module>
    from scapy.all import ARP, IP, ICMP, Ether, sr1, srp
  File "/Users/adyrcz/.local/share/virtualenvs/kube-hunter-lLs8vCzO/lib/python3.7/site-packages/scapy/all.py", line 27, in <module>
    from scapy.route import *
  File "/Users/adyrcz/.local/share/virtualenvs/kube-hunter-lLs8vCzO/lib/python3.7/site-packages/scapy/route.py", line 194, in <module>
    conf.route = Route()
  File "/Users/adyrcz/.local/share/virtualenvs/kube-hunter-lLs8vCzO/lib/python3.7/site-packages/scapy/route.py", line 27, in __init__
    self.resync()
  File "/Users/adyrcz/.local/share/virtualenvs/kube-hunter-lLs8vCzO/lib/python3.7/site-packages/scapy/route.py", line 35, in resync
    self.routes = read_routes()
  File "/Users/adyrcz/.local/share/virtualenvs/kube-hunter-lLs8vCzO/lib/python3.7/site-packages/scapy/arch/unix.py", line 82, in read_routes
    netif = rt[4 + mtu_present + prio_present + refs_present + locked]
IndexError: list index out of range
```
I removed the version pinning and installed the modules and I'm up and running now...
I dont have the time right now, but I'll go back and return the versions to the pinned version from the reqirements.txt to determine which module is causing the indexerror.

**Comment by iYehuda** [comment]
Hi @yusufscott , thanks for reporting!

I tried to reproduce the error you get by installing your `pip freeze` state inside `python:3.7.4` docker container.
Running `./kube-hunter.py --remote <my-cluster-ip>` finished successfully.

Do you use the current master branch (8cc90db)?
Can you provide the command line you used to run kube-hunter?
What type of cluster did you scan (GKE, EKS, etc.)?

**Comment by iYehuda** [comment]
I suspect this is a macOS issue, let me dig further.

**Comment by iYehuda** [comment]
This is a scapy [bug](https://github.com/secdev/scapy/issues/2134) that is [fixed](https://github.com/secdev/scapy/pull/2139) in version 2.4.3.
We need to update the requirements file respectively.
