### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by Stoffe** [aquasecurity/kube-hunter#285]
Import error trying to run kube-hunter...

(env) C:\Tools\KubeHunter\kube-hunter>.\kube-hunter.py
Traceback (most recent call last):
  File "C:\Tools\KubeHunter\kube-hunter\kube-hunter.py", line 33, in <module>
    from src.modules.report.plain import PlainReporter
  File "C:\Tools\KubeHunter\kube-hunter\src\__init__.py", line 1, in <module>
    from . import core
  File "C:\Tools\KubeHunter\kube-hunter\src\core\__init__.py", line 1, in <module>
    from . import types
  File "C:\Tools\KubeHunter\kube-hunter\src\core\types.py", line 81, in <module>
    from .events import handler # import is in the bottom to break import loops
  File "C:\Tools\KubeHunter\kube-hunter\src\core\events\__init__.py", line 1, in <module>
    from .handler import *
  File "C:\Tools\KubeHunter\kube-hunter\src\core\events\handler.py", line 4, in <module>
    from queue import Queue
ImportError: No module named queue

(env) C:\Tools\KubeHunter\kube-hunter>py --version
Python 3.7.2

**Comment by iYehuda** [comment]
Hi @Stoffe !

It seems that somehow kube-hunter is run with python2.
Can you run `python3 kube-hunter.py`?

Also can you send the out of the following commands (inside your virtual environment):
* `assoc .py`
* `ftype Python.File`
* `py -V`
* `python -V`

**Comment by iYehuda** [comment]
Closing for being stale.
