### ISSUE TITLE
AttributeError: 'L2Socket' object has no attribute 'ins'

### ISSUE THREAD

**Issue by junaid18183** [aquasecurity/kube-hunter#295]
### AttributeError: 'L2Socket' object has no attribute 'ins'

<!---
  Started a job, and checking logs of the pod

```
~ Started
~ Discovering Open Kubernetes Services...
|
| Read access to pod's service account token:
|   type: vulnerability
|   location: Local to Pod(kube-hunter-vp2xw)
|   description:
|     Accessing the pod service account token
|     gives an attacker the option to use the
|_    server API
|
| Access to pod's secrets:
|   type: vulnerability
|   location: Local to Pod(kube-hunter-vp2xw)
|   description:
|     Accessing the pod's secrets within a
|     compromised pod might disclose valuable data to a
|_    potential attacker
Exception ignored in: <function SuperSocket.__del__ at 0x7f47250e4e60>
Traceback (most recent call last):
  File "/kube-hunter/scapy/supersocket.py", line 127, in __del__
    self.close()
  File "/kube-hunter/scapy/arch/linux.py", line 481, in close
    set_promisc(self.ins, self.iface, 0)
AttributeError: 'L2Socket' object has no attribute 'ins'

----------

Vulnerabilities
+----------------------+-------------+----------------------+----------------------+----------------------+
| LOCATION             | CATEGORY    | VULNERABILITY        | DESCRIPTION          | EVIDENCE             |
+----------------------+-------------+----------------------+----------------------+----------------------+
| Local to Pod(kube-   | Access Risk | Read access to pod's |  Accessing the pod   | eyJhbGciOiJSUzI1NiIs |
| hunter-vp2xw)        |             | service account      | service account      | ImtpZCI6IiJ9.eyJpc3M |
|                      |             | token                | token gives an       | ...                  |
|                      |             |                      | attacker the option  |                      |
|                      |             |                      | to use the server    |                      |
|                      |             |                      | API                  |                      |
+----------------------+-------------+----------------------+----------------------+----------------------+
| Local to Pod(kube-   | Access Risk | Access to pod's      |  Accessing the pod's | ['/var/run/secrets/k |
| hunter-vp2xw)        |             | secrets              | secrets within a     | ubernetes.io/service |
|                      |             |                      | compromised pod      | ...                  |
|                      |             |                      | might disclose       |                      |
|                      |             |                      | valuable data to a   |                      |
|                      |             |                      | potential attacker   |                      |
+----------------------+-------------+----------------------+----------------------+----------------------+
```

**Comment by iYehuda** [comment]
Hi @junaid18183 !

Please supply some information about your setup: python version, `pip freeze` output, kube-hunter version/commit used.

**Comment by mag009** [comment]
@iYehuda  when you run kube-hunter with 

```
                    securityContext:
                      capabilities:
                        drop:
                          - NET_RAW
```
I doubt it's the expected behavior :)

**Comment by iYehuda** [comment]
This is truly a permission error.
kube-hunter requires CAP_NET_RAW for doing some discovery operations.
We try to minimize its usage as mentioned in #138.
