### ISSUE TITLE
Debug logs showing unexpected error in EtcdRemoteAccessActive

### ISSUE THREAD

**Issue by lizrice** [aquasecurity/kube-hunter#348]
`python3 kube_hunter --active --log DEBUG`

Logs include:
```
2020-04-29 15:18:23,334 DEBUG kube_hunter.modules.hunting.etcd Trying to write keys remotely on host 127.0.0.1
2020-04-29 15:18:23,334 DEBUG kube_hunter.core.events.handler 'EtcdRemoteAccessActive' object has no attribute 'protocol'
Traceback (most recent call last):
  File "/mac/kube-hunter/kube_hunter/core/events/handler.py", line 137, in worker
    hook.execute()
  File "/mac/kube-hunter/kube_hunter/modules/hunting/etcd.py", line 101, in execute
    if self.db_keys_write_access():
  File "/mac/kube-hunter/kube_hunter/modules/hunting/etcd.py", line 91, in db_keys_write_access
    f"{self.protocol}://{self.event.host}:{ETCD_PORT}/v2/keys/message",
AttributeError: 'EtcdRemoteAccessActive' object has no attribute 'protocol'
```

**Comment by danielsagi** [comment]
This was solved in #360
