### ISSUE TITLE
Support Python 3

### ISSUE THREAD

**Issue by nlamirault** [aquasecurity/kube-hunter#41]
I try kube-hunter using a virtualenv in Python 3 : 

```
$ git clone git@github.com:aquasecurity/kube-hunter.git
$ cd kube-hunter
$ python3 -m venv venv
$ . venv/bin/activate
$ pip3 install -r requirements.txt
[...]
Successfully installed PrettyTable-0.7.2 certifi-2018.8.24 chardet-3.0.4 enum34-1.1.6 idna-2.7 netifaces-0.10.7 requests-2.19.1 ruamel.yaml-0.15.64 scapy-2.4.0 urllib3-1.23
$  python ./kube-hunter.py 
Traceback (most recent call last):
  File "./kube-hunter.py", line 34, in <module>
    from src.modules.report.plain import PlainReporter
  File "/home/rock64/Projects/kube-hunter/src/__init__.py", line 1, in <module>
    import core
ImportError: No module named 'core'
```

**Comment by janiko71** [comment]
kube-hunter seems to be a Python 2.7 program. But a pull request for a Python 3 support may be useful.

**Comment by lizrice** [comment]
We really need to support Python 3

**Comment by nlamirault** [comment]
Great !
