### ISSUE TITLE
issue with local usage of ./kube-hunter.py

### ISSUE THREAD

**Issue by ThormaehlenFred** [aquasecurity/kube-hunter#56]
Today I cloned [kube-hunter](https://github.com/aquasecurity/kube-hunter.git) to:

1. an Ubuntu VM
2. the local Windows Bash on Ubuntu (Linux Subsystem on Windows) 
3. on local Windows

On the two Ubuntu vms (1 and 2) running ./kube-hunter.py --list returns the following error:
```
$ ./kube-hunter.py --list
Traceback (most recent call last):
  File "./kube-hunter.py", line 34, in <module>
    from src.modules.report.plain import PlainReporter
  File "/home/ubuntu/git/kube-hunter/src/__init__.py", line 2, in <module>
    import modules
  File "/home/ubuntu/git/kube-hunter/src/modules/__init__.py", line 1, in <module>
    import report
  File "/home/ubuntu/git/kube-hunter/src/modules/report/__init__.py", line 7, in <module>
    exec('from {} import *'.format(module_name))
  File "<string>", line 1, in <module>
  File "/home/ubuntu/git/kube-hunter/src/modules/report/yaml.py", line 3, in <module>
    from ruamel.yaml import YAML
ImportError: No module named ruamel.yaml
```
In Windows cmd (3) running ./kube-hunter.py --list returns the following error:
```
>kube-hunter.py --list
Traceback (most recent call last):
  File "C:\Users\myuser\git\kube-hunter\kube-hunter.py", line 34, in <module>
    from src.modules.report.plain import PlainReporter
  File "C:\Users\myuser\git\kube-hunter\src\__init__.py", line 1, in <module>
    import core
ImportError: No module named 'core'
```
Running kube-hunter in a [pod](https://github.com/aquasecurity/kube-hunter#pod) on Kubernetes works fine. But currently I am not able to use the local version of kube-hunter.

**Comment by leszekbulawa** [comment]
It looks like dependencies are not installed. Are you sure you did `pip install -r requirements.txt`?
Running it in a pod goes fine because requirements are already installed on the docker image.

**Comment by leszekbulawa** [comment]
You might want to consider using virtualenv. It gives nice isolation. Cheers!
